#!/bin/zsh

alias fsc-gvt='/usr/local/bin/searchd --stop --config "/Users/cjharrelson/development/iberon/gvt-us/config/development.sphinx.conf"'
alias ps-searchd='ps -ea | grep "searchd"'

alias dev-archivalock='cd archivalock && mate .'
alias dev-archivalock-ipad='cd titaniumdev/ArchivaLock && mate .'
alias dev-archivalock_marketing='cd personal/archivalock_marketing && mate .'
alias dev-fluid_digital='cd fluid_digital && mate .'
alias dev-fixed_width_parser='cd gemdev/fixed_width_parser && mate .'
alias dev-geonames_client='cd gemdev/geonames_client && mate .'
alias dev-gvtus='cd gvtus && mate .'
alias dev-guilded='cd gemdev/guilded && mate .'
alias dev-g_already_grid='cd gemdev/g_already_grid && mate .'
alias dev-hei='cd hei && mate .'
alias dev-medicce='cd medicce && mate .'
alias dev-ncite_server='cd ncite_server && mate .'
alias dev-ninja-deploy='cd gemdev/ninja-deploy && mate .'
alias dev-s3utils='cd gemdev/s3utils && mate .'
alias dev-trabajos='cd gemdev/trabajos && mate .'
